# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import upthor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryFileWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=upthor.models.thor_upload_file_name)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('md5sum', models.CharField(max_length=36, unique=True)),
                ('content_type', models.CharField(default='application/unknown', max_length=128, verbose_name='content_type')),
                ('linked', models.BooleanField(default=False)),
            ],
        ),
    ]
